[build]

[target.x86_64-pc-windows-msvc]
rustflags = [
    "-C",
    "target-feature=+crt-static",
    "-C",
    "control-flow-guard",
    "-C",
    "link-args=/MANIFEST:EMBED /CETCOMPAT /NODEFAULTLIB:libucrt.lib /DEFAULTLIB:ucrt.lib",
]

[target.aarch64-pc-windows-msvc]
rustflags = [
    "-C",
    "target-feature=+crt-static",
    "-C",
    "control-flow-guard",
    "-C",
    "link-args=/MANIFEST:EMBED /NODEFAULTLIB:libucrt.lib /DEFAULTLIB:ucrt.lib",
]

[profile.release]
lto = true
